In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./clean_optionB_300.csv")

In [3]:
df

,segment_id,segment_name,segment_type,start_x,start_y,end_x,end_y,start_lon,start_lat,end_lon,end_lat,length_m,geom_wkt
0,TRAIL-001,금정로 1,금정로 1-1,207506.115596,291321.975419,207254.366629,291366.196651,129.082444,35.218347,129.079679,35.218747,1210.398326,LINESTRING (207506.1155958843 291321.975418799...
1,TRAIL-002,금정로 2,금정로 2-1,205071.373799,294917.782961,204659.515574,295689.367692,129.055724,35.250773,129.051203,35.257730,1126.462208,LINESTRING (205071.3737990296 294917.782960737...
2,TRAIL-003,금정로 2,금정로 2-2,204659.515574,295689.367692,204944.943524,296567.702904,129.051203,35.257730,129.054345,35.265645,1126.462208,LINESTRING (204659.51557364553 295689.36769157...
3,TRAIL-004,금정로 3,금정로 3-1,204600.874042,298101.222625,204563.930105,298077.217727,129.050572,35.279469,129.050166,35.279253,46.316786,LINESTRING (204600.8740422887 298101.222625390...
4,TRAIL-005,금정로 4,금정로 4-1,203628.510463,303987.585513,203534.808635,303126.631667,129.039910,35.332529,129.038876,35.324769,958.029441,LINESTRING (203628.5104626814 303987.585512884...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,TRAIL-296,금정로 75,금정로 75-6,204543.111467,297488.237878,204162.739763,296978.878995,129.049934,35.273944,129.045750,35.269355,957.635898,LINESTRING (204543.11146730336 297488.23787831...
296,TRAIL-297,금정로 75,금정로 75-7,204162.739763,296978.878995,204537.576130,296255.835693,129.045750,35.269355,129.049866,35.262836,957.635898,LINESTRING (204162.73976275674 296978.87899462...
297,TRAIL-298,금정로 75,금정로 75-8,204537.576130,296255.835693,204674.844069,295453.656592,129.049866,35.262836,129.051370,35.255605,957.635898,LINESTRING (204537.57612969223 296255.83569291...
298,TRAIL-299,금정로 76,금정로 76-1,205911.673909,296348.304164,206775.663968,296514.339167,129.064967,35.263662,129.074464,35.265153,1044.296361,LINESTRING (205911.6739085045 296348.304163844...
299,TRAIL-300,금정로 76,금정로 76-2,206775.663968,296514.339167,207748.718369,296561.563979,129.074464,35.265153,129.085158,35.265572,1044.296361,LINESTRING (206775.66396827187 296514.33916735...

In [4]:
aaa = pd.read_csv("./금정산_등산로_이름추가.csv")

In [5]:
aaa

,segment_id,segment_name,segment_type,start_x,start_y,end_x,end_y,start_lon,start_lat,end_lon,end_lat,length_m,geom_wkt,mid_lat,mid_lon,nearest_poi,nearest_poi_dist_km,trail_label_kor,segment_label_kor
0,TRAIL-001,금정로 1,금정로 1-1,207506.115596,291321.975419,207254.366629,291366.196651,129.082444,35.218347,129.079679,35.218747,1210.398326,LINESTRING (207506.1155958843 291321.975418799...,35.218547,129.081062,온천장,0.581505,온천장 주변 순환로,온천장 주변 순환로 1구간
1,TRAIL-002,금정로 2,금정로 2-1,205071.373799,294917.782961,204659.515574,295689.367692,129.055724,35.250773,129.051203,35.257730,1126.462208,LINESTRING (205071.3737990296 294917.782960737...,35.254251,129.053463,북문,2.391351,북문 주변 순환로,북문 주변 순환로 1구간
2,TRAIL-003,금정로 2,금정로 2-2,204659.515574,295689.367692,204944.943524,296567.702904,129.051203,35.257730,129.054345,35.265645,1126.462208,LINESTRING (204659.51557364553 295689.36769157...,35.261687,129.052774,북문,1.597185,북문 주변 순환로,북문 주변 순환로 2구간
3,TRAIL-004,금정로 3,금정로 3-1,204600.874042,298101.222625,204563.930105,298077.217727,129.050572,35.279469,129.050166,35.279253,46.316786,LINESTRING (204600.8740422887 298101.222625390...,35.279361,129.050369,고당봉,0.086116,고당봉 주변 순환로,고당봉 주변 순환로 1구간
4,TRAIL-005,금정로 4,금정로 4-1,203628.510463,303987.585513,203534.808635,303126.631667,129.039910,35.332529,129.038876,35.324769,958.029441,LINESTRING (203628.5104626814 303987.585512884...,35.328649,129.039393,고당봉,5.491486,고당봉–범어사 등산로,고당봉–범어사 등산로 1구간
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,TRAIL-296,금정로 75,금정로 75-6,204543.111467,297488.237878,204162.739763,296978.878995,129.049934,35.273944,129.045750,35.269355,957.635898,LINESTRING (204543.11146730336 297488.23787831...,35.271649,129.047842,고당봉,0.973700,북문 주변 순환로,북문 주변 순환로 6구간
296,TRAIL-297,금정로 75,금정로 75-7,204162.739763,296978.878995,204537.576130,296255.835693,129.045750,35.269355,129.049866,35.262836,957.635898,LINESTRING (204162.73976275674 296978.87899462...,35.266095,129.047808,북문,1.376191,북문 주변 순환로,북문 주변 순환로 7구간
297,TRAIL-298,금정로 75,금정로 75-8,204537.576130,296255.835693,204674.844069,295453.656592,129.049866,35.262836,129.051370,35.255605,957.635898,LINESTRING (204537.57612969223 296255.83569291...,35.259221,129.050618,북문,1.918503,북문 주변 순환로,북문 주변 순환로 8구간
298,TRAIL-299,금정로 76,금정로 76-1,205911.673909,296348.304164,206775.663968,296514.339167,129.064967,35.263662,129.074464,35.265153,1044.296361,LINESTRING (205911.6739085045 296348.304163844...,35.264408,129.069716,북문,1.645100,북문–범어사 등산로,북문–범어사 등산로 1구간
299,TRAIL-300,금정로 76,금정로 76-2,206775.663968,296514.339167,207748.718369,296561.563979,129.074464,35.265153,129.085158,35.265572,1044.296361,LINESTRING (206775.66396827187 296514.33916735...,35.265363,129.079811,범어사,2.284681,북문–범어사 등산로,북문–범어사 등산로 2구간